services:
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/app
        depends_on:
            - mysql
            - redis
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "${APP_HOST_PORT}:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        ports:
            - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis-server
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
